/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainPackage_Main */

#ifndef _Included_mainPackage_Main
#define _Included_mainPackage_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mainPackage_Main
 * Method:    nativeDefiniteParallelIntegralCalculation
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_mainPackage_Main_nativeDefiniteParallelIntegralCalculation
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     mainPackage_Main
 * Method:    nativeDefiniteSequentialIntegralCalculation
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_mainPackage_Main_nativeDefiniteSequentialIntegralCalculation
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
